services:
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=red-db
    ports:
      - "5432:5432"
    volumes:
     - ./sql/Order.csv:/csvs/Order.csv
     - ./sql/product.csv:/csvs/product.csv
     - ./sql/country.csv:/csvs/country.csv
     - ./sql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 15
