#!/bin/bash
EXPECTED_RESPONSE='[{"name":"Kuwait","description": "no_description"}, {"name":"Argentina","description": "no_description"}, {"name":"Sweden","description": "no_description"}, {"name":"Cabo Verde","description": "no_description"}, {"name":"North Korea","description": "no_description"}, {"name":"North Macedonia","description": "no_description"}, {"name":"Bahamas","description": "no_description"}, {"name":"Solomon Islands","description": "no_description"}, {"name":"Zimbabwe","description": "no_description"}, {"name":"FNLA Angola*","description": "no_description"}, {"name":"China","description": "no_description"}, {"name":"Bulgaria","description": "no_description"}, {"name":"Belgium","description": "no_description"}, {"name":"Myanmar","description": "no_description"}, {"name":"Finland","description": "no_description"}, {"name":"Nepal","description": "no_description"}, {"name":"South Sudan","description": "no_description"}, {"name":"Croatia","description": "no_description"}, {"name":"Mali","description": "no_description"}, {"name":"unknown suppliers","description": "no_description"}, {"name":"NLA Macedonia*","description": "no_description"}, {"name":"Marshall Islands","description": "no_description"}, {"name":"PIJ Israel/Palestine*","description": "no_description"}, {"name":"New Zealand","description": "no_description"}, {"name":"El Salvador","description": "no_description"}, {"name":"Oman","description": "no_description"}, {"name":"Botswana","description": "no_description"}, {"name":"Togo","description": "no_description"}, {"name":"PLO Israel*","description": "no_description"}, {"name":"Bosnia-Herzegovina","description": "no_description"}, {"name":"Turkmenistan","description": "no_description"}, {"name":"Brunei","description": "no_description"}, {"name":"Kiribati","description": "no_description"}, {"name":"RPF Rwanda*","description": "no_description"}, {"name":"United Wa State Myanmar*","description": "no_description"}, {"name":"Portugal","description": "no_description"}, {"name":"Tuvalu","description": "no_description"}, {"name":"Kyrgyzstan","description": "no_description"}, {"name":"Saint Vincent","description": "no_description"}, {"name":"Angola","description": "no_description"}, {"name":"Russia","description": "no_description"}, {"name":"Canada","description": "no_description"}, {"name":"Georgia","description": "no_description"}, {"name":"Philippines","description": "no_description"}, {"name":"Kenya","description": "no_description"}, {"name":"Czechoslovakia","description": "no_description"}, {"name":"Northern Alliance Afghanistan*","description": "no_description"}, {"name":"Libya GNC","description": "no_description"}, {"name":"Palestine","description": "no_description"}, {"name":"Timor-Leste","description": "no_description"}]'

ACTUAL_RESPONSE=$(curl localhost:8080/server/api/clients)

if [ "$EXPECTED_RESPONSE" == "$ACTUAL_RESPONSE" ]; then
  echo "Test passed: Responses match."
else
  echo "Test failed: Responses do not match."
  diff -y "$EXPECTED_RESPONSE" "$ACTUAL_RESPONSE" 
  exit 1
fi

EXPECTED_RESPONSE='[{"name":"Palau","description": "no_description"}, {"name":"France","description": "no_description"}, {"name":"Suriname","description": "no_description"}, {"name":"Djibouti","description": "no_description"}, {"name":"Peru","description": "no_description"}, {"name":"Luxembourg","description": "no_description"}, {"name":"UNITA Angola*","description": "no_description"}, {"name":"ELF Ethiopia*","description": "no_description"}, {"name":"Gambia","description": "no_description"}, {"name":"LRA Uganda*","description": "no_description"}, {"name":"RUF Sierra Leone*","description": "no_description"}, {"name":"Ecuador","description": "no_description"}, {"name":"Belize","description": "no_description"}, {"name":"Chile","description": "no_description"}, {"name":"Moldova","description": "no_description"}, {"name":"Viet Nam","description": "no_description"}, {"name":"Biafra","description": "no_description"}, {"name":"South Yemen","description": "no_description"}, {"name":"Poland","description": "no_description"}, {"name":"Maldives","description": "no_description"}, {"name":"Anti-Castro rebels Cuba*","description": "no_description"}, {"name":"Jordan","description": "no_description"}, {"name":"Regional Security System**","description": "no_description"}, {"name":"FAN Chad*","description": "no_description"}, {"name":"unknown recipients","description": "no_description"}, {"name":"Uganda","description": "no_description"}, {"name":"Sri Lanka","description": "no_description"}, {"name":"Khmer Rouge Cambodia*","description": "no_description"}, {"name":"United Nations**","description": "no_description"}, {"name":"NTC Libya*","description": "no_description"}, {"name":"Panama","description": "no_description"}, {"name":"ZAPU Zimbabwe*","description": "no_description"}, {"name":"Kurdistan Regional Government Iraq*","description": "no_description"}, {"name":"Ethiopia","description": "no_description"}, {"name":"Iran","description": "no_description"}, {"name":"Norway","description": "no_description"}, {"name":"Southern rebels Yemen*","description": "no_description"}, {"name":"Paraguay","description": "no_description"}, {"name":"OSCE**","description": "no_description"}, {"name":"Spain","description": "no_description"}, {"name":"Libya HoR*","description": "no_description"}, {"name":"Haiti","description": "no_description"}, {"name":"MNLF Philippines*","description": "no_description"}, {"name":"Italy","description": "no_description"}, {"name":"Ukraine Rebels*","description": "no_description"}, {"name":"UIC Somalia*","description": "no_description"}, {"name":"Viet Minh France*","description": "no_description"}, {"name":"Lithuania","description": "no_description"}, {"name":"Turkiye","description": "no_description"}, {"name":"Saudi Arabia","description": "no_description"}]'
ACTUAL_RESPONSE=$(curl http://localhost:8080/server/api/clients?page=2)

if [ "$EXPECTED_RESPONSE" == "$ACTUAL_RESPONSE" ]; then
  echo "Test passed: Responses match."
  exit 0
else
  echo "Test failed: Responses do not match."
  diff -y "$EXPECTED_RESPONSE" "$ACTUAL_RESPONSE" 
  exit 2
fi
